---
builders:
- access_key: "{{user `aws_access_key`}}"
  ami_block_device_mappings:
  - delete_on_termination: true
    device_name: "/dev/sda1"
    volume_type: gp2
  ami_description: "{{user `description`}}"
  ami_name: "{{user `ami_name`}}{{timestamp}}"
  ami_virtualization_type: hvm
  associate_public_ip_address: true
  instance_type: t2.micro
  region: us-east-1
  secret_key: "{{user `aws_secret_key`}}"
  security_group_id: "{{user `sec_grp_id`}}"
  source_ami: "{{user `image_id`}}"
  ssh_username: root
  subnet_id: "{{user `subnet`}}"
  tags:
    organization: devops
    role: packer-creator
  type: amazon-ebs
  vpc_id: "{{user `vpc`}}"
post-processors: 
provisioners:
- execute_command: sudo {{.Vars}} sh {{.Path}}
  scripts:
  - scripts/update.sh
  - scripts/install.sh
  - scripts/cleanup.sh
  type: shell
variables:
  ami_name: centos6.6-cloud-init
  aws_access_key: "{{env `AWS_ACCESS_KEY_ID`}}"
  aws_secret_key: "{{env `AWS_SECRET_ACCESS_KEY`}}"
  description: Base image for creating new AMIs
  image_id: ami-c2a818aa
  sec_grp_id: "{{env `PACKER_SG`}}"
  subnet: "{{env `PACKER_SN`}}"
  vpc: "{{env `PACKER_VPC`}}"
